### ISSUE TITLE
npz model

### ISSUE THREAD

**Issue by JoseGomesJPG** [robot-perception-group/USMPL#1]
Hello,

I am trying to get this plugin to run. However, I am stuck at step 2 (where I am supposed to obtain csmpl.dll), because I cannot find the .npz SMPL model, only the .pkl one. Could you provide some help?

Also, I would like to know whether the plugin supports collisions (if the character bumps into an object, will they fall over, for example, or if unstable, will the character fall)?

Thank you, and great work.

**Comment by nitin-ppnp** [comment]
Hi, sorry for the late reply. The model weights are now available on SMPL website (https://smpl.is.tue.mpg.de).
The plugin doesn't support collisions. Due to limited developers, we are not actively maintaining this plugin. If enough people are interested and willing to contribute, we can add features such as collisions.

**Comment by JoseGomesJPG** [comment]
Thanks!
